CREATE SEQUENCE "HIBERNATE_SEQUENCE" START WITH 2;
CREATE MEMORY TABLE "MESSAGE"(
    "ID" BIGINT NOT NULL,
    "AUTHOR" VARCHAR(255),
    "MESSAGE" VARCHAR(255)
);
ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY("ID");